# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brain Hackers Wiki
author: Brain Hackers
description: >- # this means to ignore newlines until "baseurl:"
  The Wiki of Brain Hackers
twitter_username: brainhackerz
github_username: brain-hackers
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
locale: ja
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - '*/node_modules'
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

og_image: "assets/images/og_image.jpg"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/brainhackerz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brain-hackers"
    - label: "Brainux.org"
      icon: "fas fa-globe-asia"
      url: "https://brainux.org/"

defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      comments: true
      show_date: false
      toc: true
      toc_sticky: true

tag_archive:
  type: liquid
  path: /tags/

collections_dir: collections

collections_order:
  - beginners
  - build
  - u-boot
  - linux
  - tips
  - meta

collections:
  beginners:
    output: true
    name: For Beginners
    order:
      - get-started.md
      - roadmap.md
  build:
    output: true
    name: 手動ビルド
    order:
      - uboot.md
      - linux.md
      - copy-sd-card.md
  u-boot:
    output: true
    name: U-Boot
    order:
     - boot-eboot.md
     - boot-usb.md
  linux:
    output: true
    name: Linux
    order:
      - package-list.md
  tips:
    output: true
    name: Tips
  meta:
    output: true
    name: Meta
